[General]
uLargeRefLODGridSize=37

[Display]
bUseFilmicCurve=1
fFilmicWhiteScale=10
fglobalbrightnessboost=-0.2
fglobalcontrastboost=0.0
fglobalsaturationboost=0.3
;fSAOIntensity=10 ; SSE ambient oclusion intensity. Disabled in VR. Default is 15 for SSE. This line has no effect as long as it starts with ";"

;Lens Flare
bIBLFEnable=0 ; Disables SSE lens flare
fIBLFAnamorphicsIntensity=0.0000
fIBLFAnamorphicsIntensityFar=0.0000
fIBLFGlobalIntensity=0.0000
